"""KIRA housekeeping: memory backups and the plugin generator.

- ``backup_memory`` snapshots kira_memory.db (safe: the DB is only touched
  by sqlite in the same process; the file is copied after a checkpoint) and
  rotates kira_backups/ (newest kept, KIRA_BACKUP_KEEP default 5).
- ``generate_plugin`` has the programming agent write a real plugin file in
  plugins/ with the exact metadata convention (PLUGIN_AGENT, descriptions,
  args, consequential), then it loads hot via kira_plugins.
"""
from datetime import datetime
from pathlib import Path
import os
import re
import shutil
import sqlite3

_BACKUP_SOURCE = "kira_memory.db"


def backup_memory(keep=5):
    """Copy the memory DB into kira_backups/, rotate old copies."""
    source = Path(__file__).resolve().parent / _BACKUP_SOURCE
    if not source.exists():
        return {"ok": False, "error": f"{_BACKUP_SOURCE} not found.",
                "error_code": "db_missing"}
    # Checkpoint WAL so the copy is complete.
    try:
        connection = sqlite3.connect(str(source))
        connection.execute("PRAGMA wal_checkpoint(TRUNCATE)")
        connection.close()
    except sqlite3.Error:
        pass
    backup_dir = Path(__file__).resolve().parent / "kira_backups"
    try:
        backup_dir.mkdir(exist_ok=True)
        stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        target = backup_dir / f"kira_memory-{stamp}.db"
        shutil.copy2(source, target)
        copies = sorted(backup_dir.glob("kira_memory-*.db"))
        keep = max(1, int(keep or 5))
        removed = 0
        for old in copies[:-keep]:
            old.unlink()
            removed += 1
        return {"ok": True, "backup": target.name, "backups_kept": len(copies) - removed,
                "removed": removed,
                "response": f"Sauvegarde créée : {target.name} "
                            f"({target.stat().st_size // 1024} Ko, "
                            f"{len(copies) - removed} copie(s) conservée(s))."}
    except OSError as error:
        return {"ok": False, "error": str(error), "error_code": "backup_failed"}


def list_backups():
    backup_dir = Path(__file__).resolve().parent / "kira_backups"
    if not backup_dir.exists():
        return {"ok": True, "backups": [], "count": 0, "response": "Aucune sauvegarde."}
    backups = [{"name": item.name, "kb": item.stat().st_size // 1024}
               for item in sorted(backup_dir.glob("kira_memory-*.db"), reverse=True)]
    return {"ok": True, "backups": backups, "count": len(backups),
            "response": f"{len(backups)} sauvegarde(s)."}


_PLUGIN_NAME_RE = re.compile(r"^[a-z][a-z0-9_]{1,30}$")


def generate_plugin(name, description):
    """Write plugins/<name>.py from a template, then load it hot."""
    name = str(name or "").strip().lower()
    description = str(description or "").strip()
    if not _PLUGIN_NAME_RE.match(name):
        return {"ok": False,
                "error": "Plugin name: lowercase letters, digits, underscore (2-31 chars).",
                "error_code": "invalid_name"}
    if not description:
        return {"ok": False, "error": "Describe what the plugin should do.",
                "error_code": "description_required"}
    plugins_dir = Path(__file__).resolve().parent / "plugins"
    target = plugins_dir / f"{name}.py"
    if target.exists():
        return {"ok": False, "error": f"plugins/{name}.py already exists.",
                "error_code": "already_exists"}
    safe_description = description.replace('"""', "'''").replace("\\", "/")
    content = f'''"""
KIRA Plugin: {name.replace("_", " ").title()} (generated by KIRA)

{description}
"""

PLUGIN_NAME = "{name.replace("_", " ").title()}"
PLUGIN_VERSION = "1.0"
PLUGIN_DESCRIPTION = "{safe_description[:150]}"
PLUGIN_AUTHOR = "KIRA (generated)"

# Managed-registry metadata: which agent hosts these tools, their schemas,
# and which ones change the outside world (approval gate applies).
PLUGIN_AGENT = "plugins"
PLUGIN_DESCRIPTIONS = {{
    "{name}_run": "{safe_description[:110]}",
}}
PLUGIN_ARGS = {{
    "{name}_run": {{"input": {{"type": str, "required": False}}}},
}}
PLUGIN_CONSEQUENTIAL = ()


def {name}_run(input: str = "") -> str:
    """TODO: implement the real behavior. Return a short text result."""
    return "{name} plugin received: " + str(input or "(nothing)")


# ─────────────────────────────────────────────
# Plugin Registration (called by kira_plugins)
# ─────────────────────────────────────────────

def register(kira_plugins_module):
    kira_plugins_module.register_action("{name}_run", {name}_run)


try:
    import kira_plugins
    register(kira_plugins)
except ImportError:
    pass
'''
    try:
        plugins_dir.mkdir(exist_ok=True)
        target.write_text(content, encoding="utf-8")
    except OSError as error:
        return {"ok": False, "error": str(error), "error_code": "write_failed"}
    # Syntax check before loading anything.
    try:
        compile(content, str(target), "exec")
    except SyntaxError as error:
        target.unlink(missing_ok=True)
        return {"ok": False, "error": f"Generated plugin has a syntax error: {error}",
                "error_code": "syntax_error"}
    import kira_plugins
    if kira_plugins.load_plugin(name):
        return {"ok": True, "plugin": name, "path": f"plugins/{name}.py",
                "tool": f"{name}_run",
                "response": f"Plugin « {name} » créé et chargé — outil « {name}_run » disponible."}
    return {"ok": True, "plugin": name, "path": f"plugins/{name}.py",
            "loaded": False,
            "response": f"Plugin « {name} » créé dans plugins/ — chargez-le via la vue Agents."}
